### ISSUE TITLE
consider moving to "joxa" org

### ISSUE THREAD

**Issue by camshaft** [joxa/joxa#74]
it looks like the name "joxa" is free on github. It might be a good idea to move joxa there along with future libraries, frameworks, guides, etc. I think it would make discoverability of the joxa ecosystem a bit nicer.

**Comment by j-pb** [comment]
joxa.org seems down.

**Comment by ericbmerritt** [comment]
Thanks, I will check and see whats wrong.

On Sun, May 10, 2015 at 6:33 PM, Jan-Paul Bultmann <notifications@github.com

**Comment by ericbmerritt** [comment]
I apparently let it expire. I have reupped. I will keep this open until things propagate.

**Comment by ericbmerritt** [comment]
Thinks are back to normal now.
