### ISSUE TITLE
crypto/rand_bytes/1 doesn't exist in more recent OTP

### ISSUE THREAD

**Issue by jdjohnston** [joxa/joxa#85]
`joxa-cmp-util/gensym-body/0` calls `crypto/rand_bytes/1` but this function is non-exisistent in more recent versions of the OTP. One consequence is that the REPL is virtually useless using current OTP.

Current OTP _does_ have `crytpto/strong_rand_bytes/1`. Maybe the change is a simple one.

**Comment by hhkbp2** [comment]
PR #87 changes the code to use `crypto/strong_rand_bytes/1', and fixes some code, and upgrades the dependencies. It should be fine to pass the compilation for Erlang/OTP 20.x.

Thanks.

**Comment by hhkbp2** [comment]
@jdjohnston PR #87 has been merged. Should fix the issue now.
