### ISSUE TITLE
make fails because of deprecation warnings while compiling cucumberl.erl

### ISSUE THREAD

**Issue by jdjohnston** [joxa/joxa#88]
I was able to work around it by compiling `cucumberl.erl` with `erlc`, but should `make` fail on warnings? Doesn't seem right.

**Comment by hhkbp2** [comment]
Could you provide more info about:

* The branch/revision of Joxa code
* the version of Erlang/OTP
* the output message of the problem you met

**Comment by jdjohnston** [comment]
Sorry, I thought it would be obvious that this was a follow-up to my previous issue.

Here's a shell log with the requested information:
==== Start log ====
/home/Build/joxa
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

/home/Build/joxa
$ PAGER=cat git show
commit 8798558703dd4c21815225ca70676d460994f8e4
Merge: 7afbe23 361d336
Author: Eric Merritt <ericbmerritt@gmail.com>
Date:   Thu Dec 27 09:46:53 2018 -0800

    Merge pull request #87 from hhkbp2/fix_compilation
    
    Fix compilation errors for Erlang/OTP 20.x


/home/Build/joxa
$ erl
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Eshell V10.2  (abort with ^G)
1> 
User switch command
 --> q

/home/Build/joxa
$ # make git-deps previously done

/home/Build/joxa
$ make
/usr/bin/rebar compile
==> cucumberl (compile)
Compiled src/cucumberl_cli.erl
Compiled src/cucumberl_gen.erl
Compiled src/cucumber_parser.erl
/home/Build/joxa/deps/cucumberl/src/cucumberl.erl:59: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
/home/Build/joxa/deps/cucumberl/src/cucumberl.erl:116: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
/home/Build/joxa/deps/cucumberl/src/cucumberl.erl:118: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
Compiling /home/Build/joxa/deps/cucumberl/src/cucumberl.erl failed:
ERROR: compile failed while processing /home/Build/joxa/deps/cucumberl: rebar_abort
/home/Build/joxa/build-support/core-build.mkf:90: recipe for target 'build' failed
make: *** [build] Error 1
==== End log ====

It's easy enough to "fix" this by compiling `cucumberl.erl` directly with `erlc` but it doesn't seem right that the `make` would fail because of deprecation warnings. Agreed?

**Comment by hhkbp2** [comment]
@jdjohnston Thanks for the info.

Previously I only test the joxa code with Erlang/OTP 20. The BIF `erlang:get_stacktrace/0` is deprecated in Erlang/OTP 21, which causes the dependency `cucumber` to fail on compilation, and then bugs `joxa` as well.

I have raised a PR https://github.com/ericbmerritt/cucumberl/pull/3 to fix this issue for `cucumber`. It should fix this issue after this PR is merged into `cucumber` and the dependency of `joxa` is upgraded.

**Comment by hhkbp2** [comment]
@jdjohnston PR #89 raised.

**Comment by jdjohnston** [comment]
@hhkbp2 Clean compile, so closing _this_ issue. See new issue regarding failed `make test`.
